name: ChatMod
version: '1.1'
main: org.pennacap.chatmod.ChatMod
api-version: 1.16
authors: [ pennacap ]
description: Chat moderation to the extreme

permissions:
  chatmod.ignore:
    description: The chat moderation ignores this person
    default: op
  chatmod.lockdownIgnore:
    description: This person can speak even during lockdown
    default: op
  chatmod.manageLockdown:
    description: This person can manage lockdowns
    default: op
  chatmod.manageMute:
    description: This person can manage mutes
    default: op
  chatmod.muteIgnore:
    description: This person can speak even during mutes
    default: op
commands:
  lockdown:
    description: Lockdown chat (no one can speak)
    aliases: [ld]
    permission: chatmod.manageLockdown
    usage: /lockdown
  unlockdown:
    description: Unlockdown chat (people can speak again)
    aliases: [uld]
    permission: chatmod.manageLockdown
    usage: /unlockdown
  mute:
    description: Mute a person (the person cannot speak)
    aliases: [m]
    permission: chatmod.manageMute
    usage: /mute <player>
  unmute:
    description: Unmute a person (the person can speak again)
    aliases: [um]
    permission: chatmod.manageMute
    usage: /unmute <player>


